### PR TITLE
added a favicon

### PR DESCRIPTION
**Pull request by edkahara**
I added a favicon using gatsby-plugin-favicon v 2.1.1. I had to use an older version of the package because newer versions only support gatsby v2 but this code uses gatsby v1. This address issue [#17347](https://github.com/freeCodeCamp/freeCodeCamp/issues/17347).

### CODE REVIEW

**Comment by gagandeepp** [comment]
already present on website @edkahara please check the website and close this PR

**Comment by zebralight** [comment]
> already present on website @edkahara please check the website and close this PR

may I ask what's meant by **already present on website**?  I'm looking at search.freecodecamp.org and not seeing a favicon being rendered.  Thanks!

**Comment by SemperDisco** [comment]
@gagandeepp One month later the favicon is still not there when looking at search.freecodecamp.org. Is anyone working on it?

**Comment by gagandeepp** [comment]
@SemperDisco - This is the current screen shot
capture

**Comment by cjdhein** [comment]
@gagandeepp 
I am seeing this today in Chrome version 70.0.3538.102
image
image

**Comment by edkahara** [comment]
Closing this PR was a mistake. @gagandeepp  the website the PR was adding a favicon to is [search.freecodecamp.org](here).
@cjdhein  I tried DMing one of the guys who maintains the repo on twitter and never heard back. This was back when I created it. When @gagandeepp said it was already on the website I closed without checking, which was clearly a mistake.

**Comment by Bouncey** [comment]
Thanks @edkahara!

**Pull request merged**
